# Generated by Django 3.2.13 on 2024-10-08 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='background_image',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
